### ISSUE TITLE
Improve Argument Description and Add a Clearer Description Of The Quickstart

### ISSUE THREAD

**Issue by iluxonchik** [jaketae/storyteller#13]
**Describe the bug**
```
$ storyteller --help
```
Does not provide you with a lot of useful information. Arguments are listed, but they are not described, as such it is not clear how the CLI should be operated. This information should also be reflected in the documentation.

**To Reproduce**

Run
```
$ storyteller --help
```

**Expected behavior**
Argument description and defaults are clear.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Any
 - Browser -
 - Version -

**Comment by jaketae** [comment]
Hi @iluxonchik, thank you for opening this issue, and my sincere apologies for the belated reply. I did not have bandwidth to maintain this project recently, and the stalebot seems to have auto-closed the issue due to inactivity. I will address your open PR. Thanks again!
