### ISSUE TITLE
Disable TTS and other features

### ISSUE THREAD

**Issue by S4lXLV** [jaketae/storyteller#20]
Hey, great work! I tried the Google Colab demo, and it actually works well. However, I have a couple of questions. How can I completely disable the TTS (Text-to-Speech) feature, as I don't want TTS in my videos? Also, I have another question: Is there any way to simplify the code to only generate images based on the story, without including SRT files, TTS, or the final video? So it becomes story(text) to images?

**Comment by jaketae** [comment]
Hi @saleham5, thanks for opening this issue! I'm glad you found it worked well.

The requested feature is currently not supported, but it should not be too hard to implement. I will add this to my list of to-do's for the next release and update this thread once it is done.

**Comment by jaketae** [comment]
Unstale
