### ISSUE TITLE
no .mp4 file in "out" folder

### ISSUE THREAD

**Issue by Joosheen** [jaketae/storyteller#21]
Hi, i have .png, .wav. and .srt files but i don't see .mp4 final file in "out" folder. Could you check it?
Regards,

**Comment by Joosheen** [comment]
?

**Comment by gandie** [comment]
Running on windows? Had same issue there. `ffmpeg` call seems broken, in detail this one https://github.com/jaketae/storyteller/blob/a1138ce73df071d26411755bdc6dd84c1defe31b/src/storyteller/model.py#L115

ffmpeg seems to handle `subtitles=` path argument differently, fixed it by replacing backslahes with slash on line _before_ this:

```python
        subtitle_path = subtitle_path.replace("\\", "/")
```

**Comment by jaketae** [comment]
Unstale
